### ISSUE TITLE
Troubleshoot likes

### ISSUE THREAD

**Issue by sarahlc888** [sarahlc888/whichtok#5]
[userLikedbyUsername](https://github.com/davidteather/TikTok-Api#the-userlikedbyusername-method) from the TikTok-Api "returns a list of a given user's liked TikToks. Returns a length of 0 if private list."

For every user I've tried, this function returns `[]`. 

I need to determine whether there is an error in the code, or if I've only been looking at accounts with private like lists. 
- Can you find some account(s) for which the function works?
- Do you have a Tiktok account? Is your like list public (see [Who can see your likes](https://newsroom.tiktok.com/en-us/post-7-controlling-what-people-see-on-your-profile) from this page to toggle it on and off). If so, can you try this on yourself?

This code snippet that prints a list of likes may help!
```python
from TikTokApi import TikTokApi
api = TikTokApi()
username = 'SOME_USER'
print(api.userLikedbyUsername(username))
```
Note: if it does work and a critical mass of users have public like lists, I will have to somehow note which users do not have public likes and either weed them out or otherwise account for them.

(I'm trying to determine if like information is something I'll be able to use in my graphs, or if too many users have private like lists / if the API function is not able to fetch them)

**Comment by califynic** [comment]
Hey @sarahlc888 I tried out this function on my laptop with my friends TikTok (which she had enabled a public like list for), and it worked.  (I don't want to give out her handle publicly, since it's not my own, or else I'd give you it so you could test it out also.)

**Comment by califynic** [comment]
Also it seems like very few users have public like lists, so you might have to forego this feature.

**Comment by sarahlc888** [comment]
Thank you for the info! Agreed, this feature doesn't seem like it will work out.
